package io.casehub.qhorus.api.message;

import java.util.Arrays;
import java.util.Set;
import java.util.stream.Collectors;

public enum MessageType {
    /** Ask for information. Receiver must RESPONSE or DECLINE. Carries correlation_id. */
    QUERY,
    /** Ask for action. Receiver must execute then DONE or FAILURE. Carries correlation_id. */
    COMMAND,
    /** Answer a QUERY. Discharges the QUERY obligation. Carries correlation_id. */
    RESPONSE,
    /** Report progress on an open COMMAND. Extends the deadline window. */
    STATUS,
    /** Refuse a QUERY or COMMAND. Requires non-empty content. */
    DECLINE,
    /** Transfer obligation to named target. Target field must be non-null. */
    HANDOFF,
    /** Signal successful completion of a COMMAND. Terminal. */
    DONE,
    /** Signal unsuccessful termination of a COMMAND. Requires non-empty content. Terminal. */
    FAILURE,
    /** Observer-only telemetry. NOT delivered to agent context. */
    EVENT;

    /** Whether this message type appears in agent context (true for all except EVENT). */
    public boolean isAgentVisible() {
        return this != EVENT;
    }

    /** Whether this type carries a correlationId (auto-generated by infrastructure). */
    public boolean requiresCorrelationId() {
        return this == QUERY || this == COMMAND;
    }

    /** Whether this type requires non-empty content. */
    public boolean requiresContent() {
        return this == DECLINE || this == FAILURE;
    }

    /** Whether this type requires a non-null target field. */
    public boolean requiresTarget() {
        return this == HANDOFF;
    }

    /** Whether this is a terminal type (no further messages expected from sender). */
    public boolean isTerminal() {
        return this == HANDOFF || this == DONE || this == FAILURE;
    }

    /**
     * Parses a comma-separated list of MessageType names.
     * Returns an empty set for null or blank input.
     *
     * @throws IllegalArgumentException if any name is not a valid MessageType
     */
    public static Set<MessageType> parseTypes(final String csv) {
        if (csv == null || csv.isBlank()) return Set.of();
        return Arrays.stream(csv.split(","))
                .map(String::trim)
                .map(MessageType::valueOf)
                .collect(Collectors.toUnmodifiableSet());
    }

    /**
     * Serializes a set of MessageType values to a canonical comma-separated string.
     * Output is sorted alphabetically by name for deterministic storage — two logically
     * equal sets always produce the same stored string.
     * Returns {@code null} for {@code null} or empty input (matching the DB column semantics).
     */
    public static String serializeTypes(final Set<MessageType> types) {
        if (types == null || types.isEmpty()) return null;
        return types.stream()
                .map(Enum::name)
                .sorted()
                .collect(Collectors.joining(","));
    }
}
