CREATE TABLE reaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL,
    emoji VARCHAR(100) NOT NULL,
    actor_id VARCHAR(255) NOT NULL,
    tenancy_id VARCHAR(255) NOT NULL DEFAULT '278776f9-e1b0-46fb-9032-8bddebdcf9ce',
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_reaction_message_emoji_actor UNIQUE (message_id, emoji, actor_id),
    CONSTRAINT fk_reaction_message FOREIGN KEY (message_id) REFERENCES message(id)
);
CREATE INDEX idx_reaction_message_id ON reaction(message_id);
